### ISSUE TITLE
Feature: Scaling option

### ISSUE THREAD

**Issue by sternschnaube** [Fruitloopins/Tabby#8]
Could you add please a scaling option feature?
Like 0.5 size, to display even more players.

**Comment by GalaxyGaming2000** [comment]
was thinking the same thing unsure how to go ahead with it

**Comment by jwkerr** [comment]
will dig around the code tomorrow and see if this is practical, if it's a simple change i will add it but if it's difficult i will have to pass up on adding and maintaining it

**Comment by jwkerr** [comment]
i tried messing around with some variables and i can't really find an elegant way to do this since it messes with headers and footers, weirdly bunches names, or some other issue, it looks like it would require changing a lot of different variables and it would be quite fidgety so i will have to pass on adding this, but it would be cool

**Comment by venaminecraft** [comment]
Hello @Fruitloopins, thanks for looking into it.
Originally - I've used a different mod for this feature, but the mod is currently outdated.
It's from @Ivan-1F, hes inactive for some time. I hope he is fine.

I should've tell you before about this mod and maybe it helps, if you get inspired or can adapt directly code from it.
https://github.com/Ivan-1F/tweakerplus
https://github.com/Ivan-1F/tweakerplus/blob/1.15.2/docs/document.md#playerListScale


If nothing else helps - thanks, you tried it at least 😊

**Comment by jwkerr** [comment]
don't think this code would apply to current versions anymore given it's age, there was even a decent difference from 1.19.3 to 1.19.4 in the PlayerListHud class
